apiVersion: v2
appVersion: v1.0.0
dependencies:
  - alias: ui-2
    name: fe-ui
    repository: https://anthoai97.github.io/cicd-pipeline-stack-for-microservices
    version: 0.0.4
description: A Helm chart for Spring Boot demo application
name: ui-2
type: application
version: "1.16.0"