name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # - name: Set up Helm
      #   uses: azure/setup-helm@v3.5
      #   with:
      #     version: v3.12.0

      # - name: Add dependency chart repos
      #   run: |
      #     helm repo add bitnami https://charts.bitnami.com/bitnami
      #     helm repo add grafana https://grafana.github.io/helm-charts
      #     helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"